### ISSUE TITLE
1주차 리마인드

### ISSUE THREAD

**Issue by InSeong-So** [humormint/javascript#1]
1. `value type`과 `reference type`
2. 동적 타입과 정적 타입의 필요성과 장점
3. `var foo;`의 결과
     ```js
     var foo;
     ```
4. 자바스크립트에서의 숫자형의 개수
5. 문자열의 변경 여부

**Comment by humormint** [comment]
## 1.`value type`과 `reference type`

### 값타입(value type) 이란?

→ 값타입(value type)은 원시타입(Primitive Type)과 비슷하다.

`number`

`string`

`boolean`

`null`

`undefined`

`symbol` (New in ECMAScript 6)

### 참조타입(reference type)이란?

값타입을 제외한 모든 데이터 타입

1. `object` (`{foo: “bar”}`)
2. `array` (`[1, 2, 3, 4]`)
3. `function (object)` ( `function foo() {}` )
4. `class` (`class foo{}`)

## 2. 동적 타입과 정적 타입의 필요성과 장점

- 정적 타입 언어

→ 변수 선언할 때 변수에 할당할 수 있는 값의 종류, 즉 데이터 타입을 사전에 선언해야한다. (명시적 타입 선언)

컴파일 시점에 타입 체크를 수행한다. 만약 타입 체크를 통과하지  못했다면 에러를 발생시키고 프로그램 실행 자체를 막는다. 이는 **타입의 일관성을 강제하여 더욱 안정적인 코드 구현을 통해 런타임에 발생하는 에러를 줄인다.**

- 동적 타입 언어

자바스크립트는 정적 타입언어와 다르게 변수를 선언할 때 타입을 선언하지 않는다 단순히 var, let, const 키워드를 사용해 변수를 선언한다. 자바스크립트 변수는 정적 타입 언어와 같이 미리 선언한 데이터 타입의 값만 할당할  수 있는 것이 아니라 어떠한 데이터 타입의 값이라도 할당할 수 있다. 

## 3. `var foo;`의 결과

`var foo;`

```jsx
var foo;
console.log(typeof foo); // output : undefined

foo = {}; // 객체
console.log(typeof foo); // object

foo = []; // 배열
console.log(typeof foo); // object

foo = functioin(); // 함수
console.log(typeof foo); // function
```

→ 자바스크립트 변수는 선언이 아닌 `할당`에 의해 타입이 결정된다. 그리고 재할당에 의해 변수의 타입은 언제든지 동적으로 변할 수 있다. 따라서 위에서 선언된 변수 `foo` 는 초기에 `undefined` 로 선언됐지만 이후 객체나 함수로 재할당에 의해 동적으로 변하였다.

## 4. 자바스크립트에서의 숫자형의 개수(6.1)

→ 하나의 숫자 타입만 존재한다. 따라서 모든 수를 실수로 처리하며, 정수를 표현하기 위한 데이터 타입은 별도로 존재하지 않는다.

## 5. 문자열의 변경 여부

→ 자바스크립트의 문자열은 원시타입이며, 변경 불가능한 값이다. 따라서 문자열이 생성되면 그 문자열을 변경할 수 없다는 것을 의미한다.

**Comment by InSeong-So** [comment]
고생하셨습니다👏👏
현 챕터까지 공부하신 내용 중 가장 중요한 부분은 `값 타입(Value Type)`과 `참조 타입(Reference Type)`이에요.

[**이 글**](https://curryyou.tistory.com/275)을 참고하시길 바랍니다👍
